import cors from 'cors';
import express from 'express';
import path from 'node:path';

import { registerRoutes } from './routes';

export function createServer() {
  const app = express();

  app.use(cors());
  app.use(express.json({ limit: '2mb' }));

  // Register API routes at /api/studio/v1
  registerRoutes(app);

  // Serve static frontend files (React build)
  // In development: apps/web/src (requires frontend build or dev server)
  // In production: dist/apps/web (generated by build)
  const frontendPath = process.env.NODE_ENV === 'production'
    ? path.join(process.cwd(), 'dist', 'apps', 'web', 'src')
    : path.join(process.cwd(), 'apps', 'web', 'src');

  app.use(express.static(frontendPath));

  // SPA fallback: serve index.html for any non-API routes
  app.get('*', (_req, res) => {
    res.sendFile(path.join(frontendPath, 'index.html'), (err) => {
      if (err) {
        res.status(404).json({ ok: false, error: 'Not found' });
      }
    });
  });

  // Error handler
  app.use((error: Error, _req: express.Request, res: express.Response, _next: express.NextFunction) => {
    res.status(500).json({ ok: false, error: error.message });
  });

  return app;
}
